# Generated by Django 5.1.1 on 2024-09-11 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('size', models.CharField(choices=[('Large', 'large'), ('Medium', 'medium'), ('Small', 'small')], default='Large', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('Pending', 'pending'), ('On delivery', 'on delivery'), ('delivered', 'delivered')], default='Pending', max_length=20)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id'], name='orders_orde_order_i_205064_idx')],
            },
        ),
    ]
